
******************TESTING**************************
10/14/2022, 12:21:29
test_fruit_is_in (__main__.MyTests) ... ok
test_hola (__main__.MyTests) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.001s

OK

******************TESTING**************************
10/14/2022, 12:21:58
test_fruit_is_in (__main__.MyTests) ... FAIL
test_hola (__main__.MyTests) ... ok

======================================================================
FAIL: test_fruit_is_in (__main__.MyTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\User\Python\Proyectos\Testing3\tests\test.py", line 17, in test_fruit_is_in
    self.assertIn(valid_word, to_check)
AssertionError: 'Frutilla' not found in ['Banana', 'Manzana', 'Pera']

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=1)

******************TESTING**************************
10/14/2022, 12:22:13
test_fruit_is_in (__main__.MyTests) ... ok
test_hola (__main__.MyTests) ... FAIL

======================================================================
FAIL: test_hola (__main__.MyTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\User\Python\Proyectos\Testing3\tests\test.py", line 11, in test_hola
    self.assertEqual(valid_word, to_check)
AssertionError: 'Hola' != 'Chau'
- Hola
+ Chau


----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=1)
